import re
from pathlib import Path
from rich.console import Console

console = Console()

class AgentTranslator:
    """
    Translates compiled context into agent-specific configuration files (CLAUDE.md, GEMINI.md, etc.)
    with tailored formatting for each provider.
    """
    
    # Regex to split content by b1CodingTool HTML comments
    # Example: <!-- b1CodingTool: Root Context -->
    SECTION_REGEX = re.compile(r"(<!-- b1CodingTool: (.*?) -->)", re.DOTALL)
    
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir
        
    def generate_files(self, agents: list[str], compiled_content: str):
        """
        Generates tailored markdown files for each target agent.
        """
        header = "<!-- THIS FILE IS AUTO-GENERATED BY b1CodingTool (b1 pair). DO NOT EDIT DIRECTLY. -->\n\n"
        
        for agent in agents:
            agent_upper = agent.upper()
            filename = f"{agent_upper}.md"
            out_path = self.project_dir / filename
            
            if agent_upper == "CLAUDE":
                formatted = self._format_claude(compiled_content)
            elif agent_upper == "GEMINI":
                formatted = self._format_gemini(compiled_content)
            elif agent_upper == "CODEX":
                formatted = self._format_codex(compiled_content)
            else:
                # Default fallback
                formatted = compiled_content
                
            final_content = header + formatted
            
            out_path.write_text(final_content, encoding="utf-8")
            console.print(f"[green]\u2714 Generated:[/green] {filename}")

    def _parse_sections(self, content: str):
        """
        Splits the compiled content into a list of (section_name, section_content) tuples.
        """
        sections = []
        
        # Find all matches of the section header
        matches = list(self.SECTION_REGEX.finditer(content))
        
        if not matches:
            return [("Context", content.strip())]
            
        for i, match in enumerate(matches):
            section_header_full = match.group(1)
            section_name = match.group(2).strip()
            
            # Start of content is after the header
            start_pos = match.end()
            
            # End of content is the start of the next header, or end of string
            if i + 1 < len(matches):
                end_pos = matches[i+1].start()
            else:
                end_pos = len(content)
                
            section_content = content[start_pos:end_pos].strip()
            sections.append((section_name, section_content))
            
        return sections

    def _format_claude(self, content: str) -> str:
        """
        Formats for Claude: Wraps in <project_context> and uses XML tags for sections.
        """
        sections = self._parse_sections(content)
        output = ["<project_context>"]
        
        for name, body in sections:
            # Convert "Root Context" -> "root_context"
            tag_name = name.lower().replace(" ", "_").replace("[", "").replace("]", "").replace("-", "_").replace(".", "_")
            # Ensure tag name is valid (simple alphanumeric + underscores)
            tag_name = re.sub(r"[^a-z0-9_]", "", tag_name)
            
            output.append(f"<{tag_name}>")
            output.append(body)
            output.append(f"</{tag_name}>")
            
        output.append("</project_context>")
        return "\n\n".join(output)

    def _format_gemini(self, content: str) -> str:
        """
        Formats for Gemini: Prepends a system directive and uses standard markdown.
        """
        preamble = (
            "You are a Gemini CLI agent specializing in software engineering tasks. "
            "Follow the project conventions and architectural patterns defined below strictly."
        )
        
        sections = self._parse_sections(content)
        output = [f"> [!IMPORTANT]\n> {preamble}\n"]
        
        for name, body in sections:
            output.append(f"## {name}")
            output.append(body)
            
        return "\n\n".join(output)

    def _format_codex(self, content: str) -> str:
        """
        Formats for Codex: Clean markdown, strips internal tracking comments.
        """
        # Strip all b1CodingTool comments
        clean_content = self.SECTION_REGEX.sub("", content).strip()
        return clean_content
