from pathlib import Path
from rich.console import Console

console = Console()

class AgentTranslator:
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir
        
    def generate_files(self, agents: list[str], compiled_content: str):
        """
        Writes out identically formatted markdown files for each target agent.
        """
        header = "<!-- THIS FILE IS AUTO-GENERATED BY b1CodingTool (b1 pair). DO NOT EDIT DIRECTLY. -->\\n\\n"
        
        for agent in agents:
            filename = f"{agent.upper()}.md"
            out_path = self.project_dir / filename
            
            # For phase 4, we use standardized markdown logic.
            # Provider specific wrappers (like XML) can be added conditionally here if needed.
            final_content = header + compiled_content
            
            out_path.write_text(final_content, encoding="utf-8")
            console.print(f"[green]\u2714 Generated:[/green] {filename}")
